spring:
  application:
    name: ledger

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}

  flyway:
    enabled: true
    schemas: ledger
    default-schema: ledger
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
