spring:
  application:
    name: ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app

  flyway:
    enabled: true
    schemas: ledger
    default-schema: ledger
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
